version: '3.8'

services:
  db:
    image: postgres:13
    container_name: favorite_products_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: favorite_products
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "favorite_products"]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: favorite_products_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pg_data:
